language: java

jdk: oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "D7RJ/1uml+QZqwxGAQljp2fM/VeCpVXpnS9r++lryGdXaL73kFM9SBCYc/c8Y/7k8CoLqsoEvl7Vujg1FwXpILsx7o7+q3TW9Es8CyTONYDsRn3i7I5ZtUbJgLK3ujOhbBqOIlsMSr5cNWbY+QaCa00uHLbs4JqFx38IYBdUF8c="
    - secure: "Vlejh5F2ntvxjnDcRJprXh/Mux5q3ofDAwH8exSX4vbwvveaI0mzH8xQDWfT3a4wJEA3XEavW+3PNOFt+aPK+HNIZE2fUzQe1r+VpwH1E/QptZc/TlYO9CjaCFgj+Rs/bQXQNBd8CJVGELMhN5CpuV3eiLTVDZn8N/ZMAPLkRbE="

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
